version: "3.8"

networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - app
    networks:
      - dev

  redis:
    image: "redis:latest"
    container_name: "todo_redis"
    ports:
      - "6379:6379"
    networks:
      - dev

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    networks:
      - dev
    volumes:
      - ./app/todo.db:/app/todo.db